name: CI

on: [push]

jobs:
    go_tests:
        name: Go tests
        strategy:
            fail-fast: false
            matrix:
                platform: [ubuntu-latest, macos-11, macos-10.15] #, windows-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v2

            - uses: actions/setup-go@v2
              with:
                go-version: '^1.16.7'

            - name: Download Go vendor packages
              run: go mod download

            - name: Build redwood.js
              run: make redwood.js/dist

            - name: Run tests
              run: go test -v ./...

